apiVersion: v1
kind: Service
metadata:
  name: object-detection
spec:
  selector:
    app: object-detection
  ports:
    - protocol: TCP
      nodePort: 30087
      targetPort: 5000
      port: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection
  labels:
    app: object-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-detection
  template:
    metadata:
      labels:
        app: object-detection
    spec:
      containers:
      - name: object-detection
        image: object-detection
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0.5"
